config/routes.rb
Rails.application.routes.draw do
  root "registrations#new"
  
  get '/signup', to: "registrations#new"
  post '/signup', to: "registrations#create"

  get 'login', to: "sessions#new"
  post '/login', to: "sessions#create" 
  delete '/logout', to: "sessions#destroy"

  get 'users/:id', to: "users#show", as: "profile"

  resources :chatrooms, param: :slug
  resources :messages
  
  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :users, through: :messages
  validates :topic, presence: true, uniqueness: true, case_sensitive: false
  before_validation :sanitize, :slugify


  def to_param
    self.slug
  end

  def slugify
    self.slug = self.topic.downcase.gsub(" ", "-")
  end

  def sanitize
    self.topic = self.topic.strip
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :messages
  has_many :chatrooms, through: :messages

  validates :username, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end


  protected

  def authenticate_user!
    redirect_to root_path unless logged_in?
  end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController

  def index
    @chatroom = Chatroom.new
    @chatrooms = Chatroom.all.order("created_at DESC")
  end

  def new
    if request.referrer.split("/").last == "chatrooms"
      flash[:notice] = nil
    end
    @chatroom = Chatroom.new
  end

  def edit
    @chatroom = Chatroom.find_by(slug: params[:slug])
  end

  def create
    @chatroom = Chatroom.new(chatroom_params)
    @chatroom.user_id = current_user.id
    @chatroom.question = 0
    if @chatroom.save
      respond_to do |format|
        format.html { redirect_to @chatroom }
        format.js
      end
    else
      respond_to do |format|
        flash[:notice] = {error: ["a chatroom with this topic already exists"]}
        format.html { redirect_to new_chatroom_path }
        format.js { render template: 'chatrooms/chatroom_error.js.erb'} 
      end
    end
  end

  def update
    chatroom = Chatroom.find_by(slug: params[:slug])
    chatroom.update(chatroom_params)
    redirect_to chatroom
  end

  def show
    @chatroom = Chatroom.find_by(slug: params[:slug])
    @message = Message.new
    @host = User.where(id: @chatroom.user_id).first
  end

  private

    def chatroom_params
      params.require(:chatroom).permit(:topic)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def create
    @chatroom = Chatroom.find(message_params[:chatroom_id])
    @host = User.find(@chatroom.user_id)
    if current_user == @host
      @chatroom.question += 1
      @chatroom.save
      message = Message.new(message_params)
      message.user = current_user
      message.content = "Question #{@chatroom.question}"
      if message.save
        ActionCable.server.broadcast 'messages',
          message: message.content,
          user: message.user.username
        head :ok
      end
      Message.where(chatroom_id: @chatroom.id, active: true).each do |yeet|
        yeet.update_attributes(active: false)
      end
    else
      if current_user.messages.where(chatroom_id: @chatroom.id, active: true).present? 
      else
        message = Message.new(message_params)
        message.user = current_user
        message.active = true 
        message.save
        message.update_attributes(content: message.created_at.strftime("%A %T.%N"))
        if message.save
          ActionCable.server.broadcast 'messages',
            message: message.content,
            user: message.user.username
          head :ok
        end
      end
    end
  end

  private

    def message_params
      params.require(:message).permit(:content, :chatroom_id)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  skip_before_action :authenticate_user!

  def new
    @user = User.new
  end

  def create 
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to chatrooms_path
    else
      redirect_to signup_path, flash[:notice] =  user.errors.messages
    end
  end

  private

    def user_params
      params.require(:user).permit(:username)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate_user!
  skip_before_action :verify_authenticity_token, only: [:destroy]
  
  def new
    @user = User.new
  end

  def create
    user = User.find_by(user_params)
    if user
      session[:user_id] = user.id
      redirect_to chatrooms_path
    else
      redirect_to login_path, flash[:notice] =  {username: ["doesn't exist"]}
    end
  end

  def destroy
    reset_session
    redirect_to root_path
  end

  private

    def user_params
      params.require(:user).permit(:username)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  skip_before_action :authenticate_user!

  def about
   
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chatrooms/_chatroom.html.erb
<li><%= link_to chatroom.topic, chatroom_path(chatroom) %></li>

app/views/chatrooms/_chatroom_form.html.erb
<div class="chatroom-form">
  <%= form_for chatroom, remote: true do |f| %>
    <div class="input-group">
      <span class="input-group-addon">name:</span>
      <%= f.text_field :topic, class: "form-control"%>
    </div>
    <%= f.submit 'Create Game', class: "btn btn-primary", id: "create-chatroom" %>
  <% end %>
</div>

app/views/chatrooms/chatroom_error.js.erb
$("input#chatroom_topic").val(" ");
$("#chatroom-errors").html("<br><%=j render partial: 'layouts/flash_errors', locals: {flash: flash}%>");

app/views/chatrooms/create.js.erb
$("input#chatroom_topic").val(" ")
$("#chatroom-errors").html(" ")
$("#chatroom-index").append('<li><%= link_to @chatroom.topic, chatroom_path(@chatroom) %></li>')

app/views/chatrooms/index.html.erb
<div class="row col-md-8 col-md-offset-2" id="chatroom-title">
  <h1>Active Games</h1>
</div>

<div class="row col-md-8 col-md-offset-2" id="chatrooms">
  <%= render partial: 'chatroom_form', locals: {chatroom: @chatroom} %>
  <div id="chatroom-errors">
    
  </div>
    <ul id="chatroom-index"> 
  <% if @chatrooms.any? %>
      <%= render @chatrooms%>
  <%else %>
    </ul>
  <% end %>
</div>

app/views/chatrooms/new.html.erb
<div class="row col-md-8 col-md-offset-2">

  <h1>Create a New Game!</h1>
    <div class="well">
      <div class="chatroom-form">
        <%= form_for @chatroom do |f| %>
          <div class="input-group">
            <span class="input-group-addon">name:</span>
            <%= f.text_field :topic, class: "form-control"%>
          </div>
          <%= f.submit class: "btn btn-primary", id: "create-chatroom" %>
        <% end %>
      </div>
    </div>

    <%= render partial: 'layouts/flash_errors'%>
</div>

app/views/chatrooms/show.html.erb
<div class="row col-md-8 col-md-offset-2">
  <h1><%= @chatroom.topic %></h1>
  <label>host:</label> <%= @host.username %>

  <div class="d-flex justify-content-center">
    <%= render partial: 'messages/message_form', locals: {message: @message, chatroom: @chatroom}%>
  </div>

<div class="panel panel-default">
  <% if @chatroom.messages.any? %>
    <div class="panel-body" id="messages">
      <%= render partial: 'messages/message', collection: @chatroom.messages%>
    </div>
  <%else%>
    <div class="panel-body hidden" id="messages">
    </div>
  <%end%>
</div>



</div>

app/views/layouts/_flash_errors.html.erb
<% if flash.notice %>
  <div class="alert alert-danger">
      <% flash.notice.each do |type, messages|%>
        <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span><%messages.each do |msg|%>
          <%=type%> <%=msg%>
        <%end%>
      <%end%>
  </div>
<%end%>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
       <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <%= render partial: 'layouts/navbar_links' %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_navbar_links.html.erb
<ul class="nav navbar-nav">
  <% if current_user %>
   <li>
    <%= link_to "new game", new_chatroom_path%>
   </li>
  <% end %>
  
  <li>
    <%= link_to "games", chatrooms_path %>
  </li> 
</ul>

<ul class="nav navbar-nav navbar-right">
  <% if current_user %>
    <li>
      <%= link_to "Log Out", logout_path, method: "delete" %>
    </li>
  <% else %>
    <li><%= link_to "Sign Up", signup_path %></li>
    <li><%= link_to "Log In", login_path %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>buzzer.cloud</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <%= favicon_link_tag 'favicon.ico' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/github-fork-ribbon-css/0.2.0/gh-fork-ribbon.min.css" />
  </head>

  <body>

  <%= render partial: 'layouts/navbar' %>

  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/messages/_message.html.erb
<p><strong><%=message.user.username%>:</strong> <%=message.content%></p>

app/views/messages/_message_form.html.erb
<% if current_user == @host %>
<%=form_for message, remote: true, class: 'd-flex justify-content-center', authenticity_token: true do |f|%>

  <%= f.hidden_field :chatroom_id, value: chatroom.id %>
  <%= f.submit "New Question", class: "btn-xlarge btn-primary", alt: "Max-width 100%", data: {send: "message"}%>
<%end%>
<div class="d-flex justify-content-center"> </div>
  <% else %>
<%=form_for message, remote: true, class: 'd-flex justify-content-center', authenticity_token: true do |f|%>

  <%= f.hidden_field :chatroom_id, value: chatroom.id %>
  <%= f.submit "Buzz", class: "btn-xlarge btn-danger", alt: "Max-width 100%", data: {send: "message"}%>
<%end%>
<div class="d-flex justify-content-center"> </div>
<% end %>

app/views/users/show.html.erb
<h1>Profile</h1>